@startuml

enum hu.webhejj.perspektive.uml.UmlClass$Kind {
    INTERFACE: 
    CLASS: 
    DATA_CLASS: 
    ENUM: 

}



class hu.webhejj.perspektive.uml.UmlName {
    qualified: String
    simple: String

}



class hu.webhejj.perspektive.uml.UmlTypeProjection {

}

hu.webhejj.perspektive.uml.UmlTypeProjection o-- "*" hu.webhejj.perspektive.uml.UmlName: types


enum hu.webhejj.perspektive.uml.UmlVisibility {
    PRIVATE: 
    PROTECTED: 
    PUBLIC: 

}



class hu.webhejj.perspektive.uml.UmlMethod {
    name: String
    parameters: List<String>

}

hu.webhejj.perspektive.uml.UmlMethod o-- "1" hu.webhejj.perspektive.uml.UmlName: returnType
hu.webhejj.perspektive.uml.UmlMethod o-- "*" hu.webhejj.perspektive.uml.UmlTypeProjection: returnTypeProjections
hu.webhejj.perspektive.uml.UmlMethod o-- "0..1" hu.webhejj.perspektive.uml.UmlVisibility: visibility


enum hu.webhejj.perspektive.uml.UmlCardinality {
    OPTIONAL: 
    SCALAR: 
    VECTOR: 

}



enum hu.webhejj.perspektive.uml.UmlMembership {
    FIELD: 
    RELATIONSHIP: 

}



class hu.webhejj.perspektive.uml.UmlProperty {
    name: String

}

hu.webhejj.perspektive.uml.UmlProperty o-- "1" hu.webhejj.perspektive.uml.UmlCardinality: cardinality
hu.webhejj.perspektive.uml.UmlProperty o-- "1" hu.webhejj.perspektive.uml.UmlMembership: membership
hu.webhejj.perspektive.uml.UmlProperty o-- "1" hu.webhejj.perspektive.uml.UmlName: type
hu.webhejj.perspektive.uml.UmlProperty o-- "*" hu.webhejj.perspektive.uml.UmlTypeProjection: typeProjections


class hu.webhejj.perspektive.uml.UmlInheritance {

}

hu.webhejj.perspektive.uml.UmlInheritance o-- "1" hu.webhejj.perspektive.uml.UmlName: type
hu.webhejj.perspektive.uml.UmlInheritance o-- "*" hu.webhejj.perspektive.uml.UmlTypeProjection: typeProjections


class hu.webhejj.perspektive.uml.UmlTypeParameter {
    name: String

}

hu.webhejj.perspektive.uml.UmlTypeParameter o-- "*" hu.webhejj.perspektive.uml.UmlName: upperBounds


class hu.webhejj.perspektive.uml.UmlClass {

}

hu.webhejj.perspektive.uml.UmlClass o-- "1" hu.webhejj.perspektive.uml.UmlClass$Kind: kind
hu.webhejj.perspektive.uml.UmlClass o-- "*" hu.webhejj.perspektive.uml.UmlMethod: methods
hu.webhejj.perspektive.uml.UmlClass o-- "1" hu.webhejj.perspektive.uml.UmlName: name
hu.webhejj.perspektive.uml.UmlClass o-- "*" hu.webhejj.perspektive.uml.UmlProperty: properties
hu.webhejj.perspektive.uml.UmlClass o-- "*" hu.webhejj.perspektive.uml.UmlInheritance: superClasses
hu.webhejj.perspektive.uml.UmlClass o-- "*" hu.webhejj.perspektive.uml.UmlTypeParameter: typeParameters


@enduml
